
import '../../globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'beeeach',
  description: 'Generated by create next app',
}

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='bg-secondary-focus min-h-screen px-3 sm:px-auto py-3 md:py-32'>
					{children}
        </div>
      </body>
    </html>
  )
}
